apiVersion: v1
kind: Secret
metadata:
  name: task-model-secret
  namespace: {{ include "task-model-app.namespace" . }}
  labels:
    {{- include "task-model-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.database.url | quote }}
