apiVersion: v1
kind: ConfigMap
metadata:
  name: task-model-config
  namespace: lab7-app
  labels:
    app: task-model
data:
  TASK_ID: "7"
  TASK_DESCRIPTION: "Task from lab_7 Kubernetes"
  TASK_PRIORITY: "4"
  TASK_STATUS: "new"
  OTEL_SERVICE_NAME: "task-model-lab7"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://tempo.observability.svc.cluster.local:4318/v1/traces"
